### ISSUE TITLE
is it work like app on android phone?

### ISSUE THREAD

**Issue by ngohuunam** [seb0uil/blynk-node-client#1]
Hi

is this module simulate app on mobile phone?

**Comment by seb0uil** [comment]
Hi,
Yeah, the idea is to replace action from mobile app by nodejs.
So instead of using my phone to do actions, I use some kind of js
```
var c = require('blynk-client');
[...]
c.connect(xxx, xxx...).then(function() {
    c.activate('1').then(function() {
        return c.hardware('1', 'v', 'w', 3, 0)
    }).then(function() {
        return c.hardware('1', 'v', 'w', 2, '20400274')
    }).then(function(){
        console.log('done')
    })
}
```

**Comment by ngohuunam** [comment]
Yeah, this is a good idea, we can build any blynk dashboard on browser or another app, is it against with blynk? are they upset with this?
